### ISSUE TITLE
Submodules are not included

### ISSUE THREAD

**Issue by mikelyons** [TannerRogalsky/love2d_template#12]
There's nothing in the `lib/middleclass` directory, and no instructions for pulling this submodule into the project.

Is this intended? are we supposed to manually drop in middleclass from another source?

**Comment by TannerRogalsky** [comment]
Hey @mikelyons, the git submodules can be initialized with the `git submodule update --init --recursive` executed at the root of the repo. This is a typical way of initializing submodules through git.

Also, not to dissuade you from using this but it has not been updated in a long time and I'm not sure if it still works optimally or at all with the current version of Love. Also, not to be abrupt but I have no intention of updating it as I don't use Love anymore.

Good luck!
